export const REGISTRAION_LOADING='LOADING';
export const REGISTRAION_RESPONS='REGISTRAION_RESPONS';
export const REGISTRAION_ERROR='REGISTRAION_ERROR'

export const LOGIN_LOADING = 'LOGING_LOADING'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_ERROR='LOGIN_ERROR'