export const TOSTIFY_POP_UP = "TOSTIFY_POP"
export const TOSTIFY_POP_DOWN = "TOSTIFY_POP_DOWN"

export const TOSTIFY_SUCCESS = "TOSTIFY_SUCCESS"
export const TOSTIFY_ERROR = "TOSTIFY_ERROR"
export const TOSTIFY_INFO = "TOSTIFY_INFO"
export const TOSTIFY_WARNING = "TOSTIFY_WARNING"

export const LOADING = "LOADING"